---
- name: hello world
  hosts: localhost 
  tasks:
  - name: install the latest version of Apache
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - php

  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes

#  - name: Roll-back
#    copy:
#      src: /etc/hosts
#      dest: /home/vagrant/hosts
#      remote_src: yes
